### ISSUE TITLE
最多只能展示100条数据希望能优化一下

### ISSUE THREAD

**Issue by bigtreenono** [golmic/GithubStarManage#2]
1 . 非常感谢作者开源的贡献
2 . 最多只能展示100条数据希望能优化一下
3 . 我已经添加成功用户级标签, 但是怎么用这个标签给某个star关联起来..?

**Comment by golmic** [comment]
2.受限于github   api。每次获取只能得到100条最新的数据，这个问题已经纳入了更新功能的范围。如果需要我可以帮你更新一下数据（因为Github Star全是公开数据，不会涉及敏感操作）
3.添加用户级标签A后，要把A标签添加到B/C/D三个Star过的项目上，那么你需要从标签列表中选择A，然后在下面的表格中勾选B/C/D。点击提交

**Comment by golmic** [comment]
你好，在今天的更新中已经操作实现了操作500条Star记录，暂不打算增加上限。
